In [1]:
pip install numpy pandas scikit-learn matplotlib seaborn scipy

Requirement already satisfied: numpy in C:\Users\ManuBansal\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (2.4.2)
Requirement already satisfied: pandas in C:\Users\ManuBansal\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (3.0.1)
Requirement already satisfied: scikit-learn in C:\Users\ManuBansal\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (1.8.0)
Requirement already satisfied: matplotlib in C:\Users\ManuBansal\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (3.10.8)
Requirement already satisfied: seaborn in C:\Users\ManuBansal\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (0.13.2)
Requirement already satisfied: scipy in C:\Users\ManuBansal\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (1.17.1)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\ManuBansal\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\ManuBansal\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: joblib>=1.3.0 in C:\Users\ManuBansal\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in C:\Users\ManuBansal\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: contourpy>=1.0.1 in C:\Users\ManuBansal\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in C:\Users\ManuBansal\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in C:\Users\ManuBansal\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from matplotlib) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in C:\Users\ManuBansal\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: packaging>=20.0 in C:\Users\ManuBansal\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from matplotlib) (26.0)
Requirement already satisfied: pillow>=8 in C:\Users\ManuBansal\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from matplotlib) (12.2.0)
Requirement already satisfied: pyparsing>=3 in C:\Users\ManuBansal\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: six>=1.5 in C:\Users\ManuBansal\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
# Importing necessary libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb
from scipy import stats
from sklearn.model_selection import train_test_split, RandomizedSearchCV, cross_val_score
from sklearn.metrics import confusion_matrix, classification_report, ConfusionMatrixDisplay, accuracy_score
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor, GradientBoostingClassifier, GradientBoostingRegressor
from sklearn.linear_model import LogisticRegression, LinearRegression
from sklearn.svm import SVC
from sklearn.impute import KNNImputer

print("All libraries imported successfully!")

All libraries imported successfully!

In [3]:
df = pd.read_csv('11_Baseketball_Team_Performance_Analysis.csv')
display(df.head())

,id,year,rank,school,games,wins,losses,win_percentage,conference_wins,conference_losses,...,offensive_rebounds,total_rebounds,assists,steals,blocks,turnovers,personal_fouls,points,opponent_points,simple_rating
0,1,2021,1,Villanova,38,30,8,0.789,16,4,...,10.3,34.8,11.9,6.0,2.2,9.9,14.9,71.7,62.7,19.31
1,2,2021,2,Providence,33,27,6,0.818,14,3,...,10.5,37.6,13.2,5.0,3.7,11.4,16.0,71.5,66.2,13.08
2,3,2021,3,UConn,33,23,10,0.697,13,6,...,13.8,40.4,14.0,5.9,6.4,11.8,16.8,74.8,65.3,16.40
3,4,2021,4,Creighton,35,23,12,0.657,12,7,...,9.6,38.1,13.3,5.5,4.3,14.1,13.6,69.2,66.4,11.34
4,5,2021,5,Marquette,32,19,13,0.594,11,8,...,7.8,34.8,16.0,7.8,5.2,12.4,17.4,74.0,71.6,11.36

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 37 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   id                               10000 non-null  int64
 1   year                             10000 non-null  int64
 2   rank                             10000 non-null  int64
 3   school                           10000 non-null  str
 4   games                            10000 non-null  int64
 5   wins                             10000 non-null  int64
 6   losses                           10000 non-null  int64
 7   win_percentage                   10000 non-null  float64
 8   conference_wins                  10000 non-null  int64
 9   conference_losses                10000 non-null  int64
 10  home_wins                        9792 non-null   float64
 11  home_losses                      9792 non-null   float64
 12  away_wins                        9792 non-null   float64
 13  away_losses                      9792 non-null   float64
 14  offensive_rating                 9722 non-null   float64
 15  defensive_rating                 9722 non-null   float64
 16  net_rating                       9722 non-null   float64
 17  field_goals                      10000 non-null  float64
 18  field_goal_attempts              10000 non-null  float64
 19  field_goal_percentage            10000 non-null  float64
 20  3_pointers                       9942 non-null   float64
 21  3_pointer_attempts               9942 non-null   float64
 22  3_pointer_percentage             9942 non-null   float64
 23  effective_field_goal_percentage  9942 non-null   float64
 24  free_throws                      10000 non-null  float64
 25  free_throw_attempts              10000 non-null  float64
 26  free_throw_percentage            10000 non-null  float64
 27  offensive_rebounds               9841 non-null   float64
 28  total_rebounds                   10000 non-null  float64
 29  assists                          9993 non-null   float64
 30  steals                           9984 non-null   float64
 31  blocks                           9981 non-null   float64
 32  turnovers                        9980 non-null   float64
 33  personal_fouls                   9981 non-null   float64
 34  points                           10000 non-null  float64
 35  opponent_points                  10000 non-null  float64
 36  simple_rating                    10000 non-null  float64
dtypes: float64(28), int64(8), str(1)
memory usage: 2.8 MB

In [5]:
df.describe()

,id,year,rank,games,wins,losses,win_percentage,conference_wins,conference_losses,home_wins,...,offensive_rebounds,total_rebounds,assists,steals,blocks,turnovers,personal_fouls,points,opponent_points,simple_rating
count,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,9792.000000,...,9841.000000,10000.000000,9993.000000,9984.000000,9981.000000,9980.000000,9981.000000,10000.000000,10000.000000,10000.000000
mean,248.412600,2000.018200,8.37160,31.367000,20.434800,13.602200,0.600213,8.545300,9.935300,11.064645,...,12.322711,36.379410,14.799860,8.009976,4.842250,14.270301,19.048081,72.791880,68.621000,11.144945
std,144.141145,12.403034,4.63839,6.107474,9.063916,6.801175,0.187888,5.143986,5.387246,4.956641,...,2.713103,4.126262,2.900883,2.153099,2.031402,2.869481,3.159739,6.641915,6.022472,5.893731
min,1.000000,1979.000000,1.00000,19.000000,5.000000,2.000000,0.194000,0.000000,1.000000,2.000000,...,7.500000,27.700000,8.800000,4.000000,1.400000,8.700000,12.700000,58.800000,53.500000,0.000000
25%,123.000000,1989.000000,4.00000,27.000000,13.000000,8.000000,0.464000,4.000000,5.000000,7.000000,...,10.100000,33.100000,12.500000,6.200000,3.200000,11.800000,16.500000,67.900000,64.300000,6.910000
50%,248.000000,2000.000000,8.00000,32.000000,20.000000,14.000000,0.618000,9.000000,10.000000,11.000000,...,12.200000,36.300000,14.700000,8.000000,4.700000,14.200000,18.900000,72.700000,68.500000,11.350000
75%,374.000000,2011.000000,12.00000,36.000000,28.000000,19.000000,0.750000,13.000000,15.000000,15.000000,...,14.400000,39.500000,17.000000,9.700000,6.300000,16.500000,21.400000,77.900000,73.200000,15.480000
max,496.000000,2021.000000,16.00000,41.000000,36.000000,25.000000,0.944000,17.000000,19.000000,19.000000,...,18.600000,45.500000,20.800000,13.100000,9.100000,20.900000,28.400000,89.700000,83.000000,26.640000

In [9]:
df = df.fillna(df.median(numeric_only=True))
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 37 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   id                               10000 non-null  int64
 1   year                             10000 non-null  int64
 2   rank                             10000 non-null  int64
 3   school                           10000 non-null  str
 4   games                            10000 non-null  int64
 5   wins                             10000 non-null  int64
 6   losses                           10000 non-null  int64
 7   win_percentage                   10000 non-null  float64
 8   conference_wins                  10000 non-null  int64
 9   conference_losses                10000 non-null  int64
 10  home_wins                        10000 non-null  float64
 11  home_losses                      10000 non-null  float64
 12  away_wins                        10000 non-null  float64
 13  away_losses                      10000 non-null  float64
 14  offensive_rating                 10000 non-null  float64
 15  defensive_rating                 10000 non-null  float64
 16  net_rating                       10000 non-null  float64
 17  field_goals                      10000 non-null  float64
 18  field_goal_attempts              10000 non-null  float64
 19  field_goal_percentage            10000 non-null  float64
 20  3_pointers                       10000 non-null  float64
 21  3_pointer_attempts               10000 non-null  float64
 22  3_pointer_percentage             10000 non-null  float64
 23  effective_field_goal_percentage  10000 non-null  float64
 24  free_throws                      10000 non-null  float64
 25  free_throw_attempts              10000 non-null  float64
 26  free_throw_percentage            10000 non-null  float64
 27  offensive_rebounds               10000 non-null  float64
 28  total_rebounds                   10000 non-null  float64
 29  assists                          10000 non-null  float64
 30  steals                           10000 non-null  float64
 31  blocks                           10000 non-null  float64
 32  turnovers                        10000 non-null  float64
 33  personal_fouls                   10000 non-null  float64
 34  points                           10000 non-null  float64
 35  opponent_points                  10000 non-null  float64
 36  simple_rating                    10000 non-null  float64
dtypes: float64(28), int64(8), str(1)
memory usage: 2.8 MB